name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels:

- enhancement
  body:
- type: markdown
  attributes:
  value: |
  Thank you for taking the time to suggest a new feature!
  Please provide as much detail as possible.

- type: textarea
  id: problem
  attributes:
  label: Problem Statement
  description: What problem or limitation are you facing?
  placeholder: I'm frustrated when...
  validations:
  required: true

- type: textarea
  id: solution
  attributes:
  label: Proposed Solution
  description: Describe the feature or enhancement you'd like to see
  placeholder: I would like the application to...
  validations:
  required: true

- type: textarea
  id: alternatives
  attributes:
  label: Alternatives Considered
  description: Have you considered any alternative solutions or workarounds?
  placeholder: Other approaches could be...
  validations:
  required: false

- type: dropdown
  id: priority
  attributes:
  label: Priority
  description: How important is this feature?
  options: - Low - Medium - High - Critical
  validations:
  required: true

- type: checkboxes
  id: scope
  attributes:
  label: Feature Scope
  options: - label: UI / UX - label: Backend / API - label: Performance - label: Security - label: Documentation - label: Other

- type: textarea
  id: additional
  attributes:
  label: Additional Context
  description: Screenshots, mockups, references, or links
  placeholder: Add any other context here...
  validations:
  required: false

- type: checkboxes
  id: confirmation
  attributes:
  label: Confirmation
  options: - label: I have searched existing issues and this feature has not been requested yet
  required: true
